# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fsp-nc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import fsp_common_pb2 as fsp__common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='fsp-nc.proto',
  package='com.fsmeeting.fsp.proto.nc',
  syntax='proto3',
  serialized_pb=_b('\n\x0c\x66sp-nc.proto\x12\x1a\x63om.fsmeeting.fsp.proto.nc\x1a\x10\x66sp-common.proto\"k\n\x12SelectStreamServer\x12\x11\n\tstream_id\x18\x01 \x01(\t\x12\x42\n\x0cstreamServer\x18\x02 \x03(\x0b\x32,.com.fsmeeting.fsp.proto.common.StreamServer\"Y\n\x15SelectStreamServerRsp\x12@\n\x08response\x18\x01 \x01(\x0b\x32..com.fsmeeting.fsp.proto.common.CommonResponse\"E\n\x18NotifyStreamSendingStart\x12\x11\n\tstream_id\x18\x01 \x01(\t\x12\x16\n\x0erecv_client_id\x18\x02 \x01(\t\"_\n\x1bNotifyStreamSendingStartRsp\x12@\n\x08response\x18\x01 \x01(\x0b\x32..com.fsmeeting.fsp.proto.common.CommonResponse\"D\n\x17NotifyStreamSendingStop\x12\x11\n\tstream_id\x18\x01 \x01(\t\x12\x16\n\x0erecv_client_id\x18\x02 \x01(\t\"^\n\x1aNotifyStreamSendingStopRsp\x12@\n\x08response\x18\x01 \x01(\x0b\x32..com.fsmeeting.fsp.proto.common.CommonResponse\"\xba\x01\n\x13NotifyPublishStream\x12\x11\n\tstream_id\x18\x01 \x01(\t\x12\x1c\n\x14stream_publish_token\x18\x02 \x01(\t\x12\x10\n\x08group_id\x18\x03 \x01(\t\x12\x0f\n\x07user_id\x18\x04 \x01(\t\x12\x10\n\x08media_id\x18\x05 \x01(\t\x12=\n\nmedia_type\x18\x06 \x01(\x0e\x32).com.fsmeeting.fsp.proto.common.MediaType\"Z\n\x16NotifyPublishStreamRsp\x12@\n\x08response\x18\x01 \x01(\x0b\x32..com.fsmeeting.fsp.proto.common.CommonResponse*\xff\x02\n\x0fProtoDictionary\x12\x19\n\x15\x45num2UnknownInterface\x10\x00\x12\x1c\n\x17\x45num2SelectStreamServer\x10\x88\'\x12\x1f\n\x1a\x45num2SelectStreamServerRsp\x10\x89\'\x12\"\n\x1d\x45num2NotifyStreamSendingStart\x10\x8a\'\x12%\n Enum2NotifyStreamSendingStartRsp\x10\x8b\'\x12!\n\x1c\x45num2NotifyStreamSendingStop\x10\x8c\'\x12$\n\x1f\x45num2NotifyStreamSendingStopRsp\x10\x8d\'\x12\x1d\n\x18\x45num2NotifyPublishStream\x10\x8e\'\x12 \n\x1b\x45num2NotifyPublishStreamRsp\x10\x8f\'\x12\x1c\n\x17\x45num2StreamSendingStart\x10\x90\'\x12\x1f\n\x1a\x45num2StreamSendingStartRsp\x10\x91\'B\'\n\x1a\x63om.fsmeeting.fsp.proto.ncP\x01\xf8\x01\x01\xa2\x02\x03GPBb\x06proto3')
  ,
  dependencies=[fsp__common__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_PROTODICTIONARY = _descriptor.EnumDescriptor(
  name='ProtoDictionary',
  full_name='com.fsmeeting.fsp.proto.nc.ProtoDictionary',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Enum2UnknownInterface', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Enum2SelectStreamServer', index=1, number=5000,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Enum2SelectStreamServerRsp', index=2, number=5001,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Enum2NotifyStreamSendingStart', index=3, number=5002,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Enum2NotifyStreamSendingStartRsp', index=4, number=5003,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Enum2NotifyStreamSendingStop', index=5, number=5004,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Enum2NotifyStreamSendingStopRsp', index=6, number=5005,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Enum2NotifyPublishStream', index=7, number=5006,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Enum2NotifyPublishStreamRsp', index=8, number=5007,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Enum2StreamSendingStart', index=9, number=5008,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Enum2StreamSendingStartRsp', index=10, number=5009,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=878,
  serialized_end=1261,
)
_sym_db.RegisterEnumDescriptor(_PROTODICTIONARY)

ProtoDictionary = enum_type_wrapper.EnumTypeWrapper(_PROTODICTIONARY)
Enum2UnknownInterface = 0
Enum2SelectStreamServer = 5000
Enum2SelectStreamServerRsp = 5001
Enum2NotifyStreamSendingStart = 5002
Enum2NotifyStreamSendingStartRsp = 5003
Enum2NotifyStreamSendingStop = 5004
Enum2NotifyStreamSendingStopRsp = 5005
Enum2NotifyPublishStream = 5006
Enum2NotifyPublishStreamRsp = 5007
Enum2StreamSendingStart = 5008
Enum2StreamSendingStartRsp = 5009



_SELECTSTREAMSERVER = _descriptor.Descriptor(
  name='SelectStreamServer',
  full_name='com.fsmeeting.fsp.proto.nc.SelectStreamServer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stream_id', full_name='com.fsmeeting.fsp.proto.nc.SelectStreamServer.stream_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='streamServer', full_name='com.fsmeeting.fsp.proto.nc.SelectStreamServer.streamServer', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=169,
)


_SELECTSTREAMSERVERRSP = _descriptor.Descriptor(
  name='SelectStreamServerRsp',
  full_name='com.fsmeeting.fsp.proto.nc.SelectStreamServerRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='com.fsmeeting.fsp.proto.nc.SelectStreamServerRsp.response', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=171,
  serialized_end=260,
)


_NOTIFYSTREAMSENDINGSTART = _descriptor.Descriptor(
  name='NotifyStreamSendingStart',
  full_name='com.fsmeeting.fsp.proto.nc.NotifyStreamSendingStart',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stream_id', full_name='com.fsmeeting.fsp.proto.nc.NotifyStreamSendingStart.stream_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='recv_client_id', full_name='com.fsmeeting.fsp.proto.nc.NotifyStreamSendingStart.recv_client_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=262,
  serialized_end=331,
)


_NOTIFYSTREAMSENDINGSTARTRSP = _descriptor.Descriptor(
  name='NotifyStreamSendingStartRsp',
  full_name='com.fsmeeting.fsp.proto.nc.NotifyStreamSendingStartRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='com.fsmeeting.fsp.proto.nc.NotifyStreamSendingStartRsp.response', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=333,
  serialized_end=428,
)


_NOTIFYSTREAMSENDINGSTOP = _descriptor.Descriptor(
  name='NotifyStreamSendingStop',
  full_name='com.fsmeeting.fsp.proto.nc.NotifyStreamSendingStop',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stream_id', full_name='com.fsmeeting.fsp.proto.nc.NotifyStreamSendingStop.stream_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='recv_client_id', full_name='com.fsmeeting.fsp.proto.nc.NotifyStreamSendingStop.recv_client_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=430,
  serialized_end=498,
)


_NOTIFYSTREAMSENDINGSTOPRSP = _descriptor.Descriptor(
  name='NotifyStreamSendingStopRsp',
  full_name='com.fsmeeting.fsp.proto.nc.NotifyStreamSendingStopRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='com.fsmeeting.fsp.proto.nc.NotifyStreamSendingStopRsp.response', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=500,
  serialized_end=594,
)


_NOTIFYPUBLISHSTREAM = _descriptor.Descriptor(
  name='NotifyPublishStream',
  full_name='com.fsmeeting.fsp.proto.nc.NotifyPublishStream',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stream_id', full_name='com.fsmeeting.fsp.proto.nc.NotifyPublishStream.stream_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stream_publish_token', full_name='com.fsmeeting.fsp.proto.nc.NotifyPublishStream.stream_publish_token', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='group_id', full_name='com.fsmeeting.fsp.proto.nc.NotifyPublishStream.group_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='com.fsmeeting.fsp.proto.nc.NotifyPublishStream.user_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='media_id', full_name='com.fsmeeting.fsp.proto.nc.NotifyPublishStream.media_id', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='media_type', full_name='com.fsmeeting.fsp.proto.nc.NotifyPublishStream.media_type', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=597,
  serialized_end=783,
)


_NOTIFYPUBLISHSTREAMRSP = _descriptor.Descriptor(
  name='NotifyPublishStreamRsp',
  full_name='com.fsmeeting.fsp.proto.nc.NotifyPublishStreamRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='com.fsmeeting.fsp.proto.nc.NotifyPublishStreamRsp.response', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=785,
  serialized_end=875,
)

_SELECTSTREAMSERVER.fields_by_name['streamServer'].message_type = fsp__common__pb2._STREAMSERVER
_SELECTSTREAMSERVERRSP.fields_by_name['response'].message_type = fsp__common__pb2._COMMONRESPONSE
_NOTIFYSTREAMSENDINGSTARTRSP.fields_by_name['response'].message_type = fsp__common__pb2._COMMONRESPONSE
_NOTIFYSTREAMSENDINGSTOPRSP.fields_by_name['response'].message_type = fsp__common__pb2._COMMONRESPONSE
_NOTIFYPUBLISHSTREAM.fields_by_name['media_type'].enum_type = fsp__common__pb2._MEDIATYPE
_NOTIFYPUBLISHSTREAMRSP.fields_by_name['response'].message_type = fsp__common__pb2._COMMONRESPONSE
DESCRIPTOR.message_types_by_name['SelectStreamServer'] = _SELECTSTREAMSERVER
DESCRIPTOR.message_types_by_name['SelectStreamServerRsp'] = _SELECTSTREAMSERVERRSP
DESCRIPTOR.message_types_by_name['NotifyStreamSendingStart'] = _NOTIFYSTREAMSENDINGSTART
DESCRIPTOR.message_types_by_name['NotifyStreamSendingStartRsp'] = _NOTIFYSTREAMSENDINGSTARTRSP
DESCRIPTOR.message_types_by_name['NotifyStreamSendingStop'] = _NOTIFYSTREAMSENDINGSTOP
DESCRIPTOR.message_types_by_name['NotifyStreamSendingStopRsp'] = _NOTIFYSTREAMSENDINGSTOPRSP
DESCRIPTOR.message_types_by_name['NotifyPublishStream'] = _NOTIFYPUBLISHSTREAM
DESCRIPTOR.message_types_by_name['NotifyPublishStreamRsp'] = _NOTIFYPUBLISHSTREAMRSP
DESCRIPTOR.enum_types_by_name['ProtoDictionary'] = _PROTODICTIONARY

SelectStreamServer = _reflection.GeneratedProtocolMessageType('SelectStreamServer', (_message.Message,), dict(
  DESCRIPTOR = _SELECTSTREAMSERVER,
  __module__ = 'fsp_nc_pb2'
  # @@protoc_insertion_point(class_scope:com.fsmeeting.fsp.proto.nc.SelectStreamServer)
  ))
_sym_db.RegisterMessage(SelectStreamServer)

SelectStreamServerRsp = _reflection.GeneratedProtocolMessageType('SelectStreamServerRsp', (_message.Message,), dict(
  DESCRIPTOR = _SELECTSTREAMSERVERRSP,
  __module__ = 'fsp_nc_pb2'
  # @@protoc_insertion_point(class_scope:com.fsmeeting.fsp.proto.nc.SelectStreamServerRsp)
  ))
_sym_db.RegisterMessage(SelectStreamServerRsp)

NotifyStreamSendingStart = _reflection.GeneratedProtocolMessageType('NotifyStreamSendingStart', (_message.Message,), dict(
  DESCRIPTOR = _NOTIFYSTREAMSENDINGSTART,
  __module__ = 'fsp_nc_pb2'
  # @@protoc_insertion_point(class_scope:com.fsmeeting.fsp.proto.nc.NotifyStreamSendingStart)
  ))
_sym_db.RegisterMessage(NotifyStreamSendingStart)

NotifyStreamSendingStartRsp = _reflection.GeneratedProtocolMessageType('NotifyStreamSendingStartRsp', (_message.Message,), dict(
  DESCRIPTOR = _NOTIFYSTREAMSENDINGSTARTRSP,
  __module__ = 'fsp_nc_pb2'
  # @@protoc_insertion_point(class_scope:com.fsmeeting.fsp.proto.nc.NotifyStreamSendingStartRsp)
  ))
_sym_db.RegisterMessage(NotifyStreamSendingStartRsp)

NotifyStreamSendingStop = _reflection.GeneratedProtocolMessageType('NotifyStreamSendingStop', (_message.Message,), dict(
  DESCRIPTOR = _NOTIFYSTREAMSENDINGSTOP,
  __module__ = 'fsp_nc_pb2'
  # @@protoc_insertion_point(class_scope:com.fsmeeting.fsp.proto.nc.NotifyStreamSendingStop)
  ))
_sym_db.RegisterMessage(NotifyStreamSendingStop)

NotifyStreamSendingStopRsp = _reflection.GeneratedProtocolMessageType('NotifyStreamSendingStopRsp', (_message.Message,), dict(
  DESCRIPTOR = _NOTIFYSTREAMSENDINGSTOPRSP,
  __module__ = 'fsp_nc_pb2'
  # @@protoc_insertion_point(class_scope:com.fsmeeting.fsp.proto.nc.NotifyStreamSendingStopRsp)
  ))
_sym_db.RegisterMessage(NotifyStreamSendingStopRsp)

NotifyPublishStream = _reflection.GeneratedProtocolMessageType('NotifyPublishStream', (_message.Message,), dict(
  DESCRIPTOR = _NOTIFYPUBLISHSTREAM,
  __module__ = 'fsp_nc_pb2'
  # @@protoc_insertion_point(class_scope:com.fsmeeting.fsp.proto.nc.NotifyPublishStream)
  ))
_sym_db.RegisterMessage(NotifyPublishStream)

NotifyPublishStreamRsp = _reflection.GeneratedProtocolMessageType('NotifyPublishStreamRsp', (_message.Message,), dict(
  DESCRIPTOR = _NOTIFYPUBLISHSTREAMRSP,
  __module__ = 'fsp_nc_pb2'
  # @@protoc_insertion_point(class_scope:com.fsmeeting.fsp.proto.nc.NotifyPublishStreamRsp)
  ))
_sym_db.RegisterMessage(NotifyPublishStreamRsp)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\032com.fsmeeting.fsp.proto.ncP\001\370\001\001\242\002\003GPB'))
# @@protoc_insertion_point(module_scope)
